plugins:
    dice_roller_enabled:
        default: true
        client: false
    dice_roller_inline_rolls:
        default: true
        client: false
    dice_roller_sum_rolls:
        default: true
        client: false
    dice_roller_append_user:
        default: 'dicebot'
        client: false
